package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func TestRenderCompositionContract(t *testing.T) {
	home := t.TempDir()
	custom := filepath.Join(home, "aliases.zsh")
	if err := os.WriteFile(custom, []byte("alias project='cd ~/src'\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	var cfg config
	input := "version: 1\nshell:\n  prompt: false\n  aliases:\n    extend:\n      path: " + custom + "\n"
	if err := yaml.Unmarshal([]byte(input), &cfg); err != nil {
		t.Fatal(err)
	}

	output := t.TempDir()
	if err := render(cfg, home, output); err != nil {
		t.Fatal(err)
	}

	aliases, err := os.ReadFile(filepath.Join(output, "15-aliases.zsh"))
	if err != nil {
		t.Fatal(err)
	}
	text := string(aliases)
	for _, expected := range []string{
		"# Generated by zshenv. Do not edit.",
		"alias ll='ls -lah'",
		"source '" + custom + "'",
	} {
		if !strings.Contains(text, expected) {
			t.Fatalf("rendered aliases missing %q:\n%s", expected, text)
		}
	}
	if _, err := os.Stat(filepath.Join(output, "16-prompt.zsh")); !os.IsNotExist(err) {
		t.Fatal("disabled prompt generated a file")
	}
}

func TestRenderReplaceExcludesDefaults(t *testing.T) {
	home := t.TempDir()
	custom := filepath.Join(home, "aliases.zsh")
	if err := os.WriteFile(custom, []byte("alias only_custom='true'\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	var cfg config
	input := "version: 1\nshell:\n  prompt: false\n  aliases:\n    path: " + custom + "\n"
	if err := yaml.Unmarshal([]byte(input), &cfg); err != nil {
		t.Fatal(err)
	}

	output := t.TempDir()
	if err := render(cfg, home, output); err != nil {
		t.Fatal(err)
	}
	aliases, err := os.ReadFile(filepath.Join(output, "15-aliases.zsh"))
	if err != nil {
		t.Fatal(err)
	}
	text := string(aliases)
	if strings.Contains(text, "alias ll=") {
		t.Fatal("replace mode retained built-in aliases")
	}
	if !strings.Contains(text, "source '"+custom+"'") {
		t.Fatal("replace mode did not source custom aliases")
	}
}
