#!/usr/bin/env python3
from __future__ import annotations

import argparse
import datetime as dt
import difflib
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    print("zshenv: PyYAML is required; see README", file=sys.stderr)
    raise SystemExit(2)

ROOT = Path(__file__).resolve().parent
HOME = Path.home()
CONFIG_DIR = Path(os.environ.get("XDG_CONFIG_HOME", HOME / ".config")) / "zsh"
CONFIG_FILE = CONFIG_DIR / "shell.yaml"
GENERATED_DIR = CONFIG_DIR / "generated"
CUSTOM_DIR = CONFIG_DIR / "custom"
LOADER = HOME / ".zshrc"
MARKER = "# managed-by: zshenv"

SEGMENTS = [
    "core",
    "paths",
    "completion",
    "integrations",
    "remote",
    "aliases",
    "prompt",
    "ux",
]
DEFAULT_FILES = {name: CONFIG_DIR / f"{name}.zsh" for name in SEGMENTS}
CONFLICT_PATTERNS = {
    "prompt initialization": r"(starship init|oh-my-posh init|powerlevel10k|p10k)",
    "tool integration": r"(mise activate|pyenv init|nvm\.sh|zoxide init|direnv hook|atuin init)",
    "completion initialization": r"\bcompinit\b",
    "aliases": r"^\s*alias\s+",
    "keybindings": r"\bbindkey\b",
}
OPTIONAL_COMMANDS = ("fzf", "zoxide", "mise", "docker", "kubectl", "tmux", "ssh")


def fail(message: str, code: int = 1) -> None:
    print(f"zshenv: {message}", file=sys.stderr)
    raise SystemExit(code)


def run(*args: str) -> None:
    try:
        subprocess.run(args, check=True)
    except FileNotFoundError:
        fail(f"command not found: {args[0]}")
    except subprocess.CalledProcessError as exc:
        fail(f"command failed ({exc.returncode}): {' '.join(args)}")


def expand_path(value: Any) -> Path:
    if not isinstance(value, str) or not value:
        fail("path must be a non-empty string")
    if any(token in value for token in ("$", "`", "*", "?", "[", "]")):
        fail(f"path must not contain shell expansion or glob syntax: {value}")
    path = Path(value).expanduser()
    if not path.is_absolute():
        fail(f"path must be absolute or start with ~: {value}")
    return path


def load_config(path: Path) -> dict[str, Any]:
    if not path.is_file():
        fail(f"config not found: {path}")
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except (OSError, yaml.YAMLError) as exc:
        fail(f"invalid YAML: {exc}")
    if data.get("version") != 1 or not isinstance(data.get("shell"), dict):
        fail("config must contain `version: 1` and a `shell` mapping")
    unknown = set(data["shell"]) - set(SEGMENTS)
    if unknown:
        fail(f"unknown shell segments: {', '.join(sorted(unknown))}")
    return data


def parse_segment(name: str, value: Any) -> tuple[str, Path | None]:
    if value is None or value == {}:
        return "default", None
    if value is False:
        return "disabled", None
    if not isinstance(value, dict):
        fail(f"shell.{name} must be an object or false")

    if name == "prompt":
        unknown = set(value) - {"engine", "path"}
        if unknown:
            fail(f"unknown shell.prompt fields: {', '.join(sorted(unknown))}")
        engine = value.get("engine", "starship")
        if engine != "starship":
            fail(f"unsupported prompt engine: {engine}")
        return ("replace", expand_path(value["path"])) if "path" in value else ("default", None)

    unknown = set(value) - {"path", "extend"}
    if unknown:
        fail(f"unknown shell.{name} fields: {', '.join(sorted(unknown))}")
    if "path" in value and "extend" in value:
        fail(f"shell.{name} cannot contain both path and extend")
    if "path" in value:
        return "replace", expand_path(value["path"])
    if "extend" in value:
        extension = value["extend"]
        if not isinstance(extension, dict) or set(extension) != {"path"}:
            fail(f"shell.{name}.extend must contain only path")
        return "extend", expand_path(extension["path"])
    fail(f"shell.{name} must be empty, false, path, or extend.path")


def quote_zsh(path: Path) -> str:
    return "'" + str(path).replace("'", "'\\''") + "'"


def source_line(path: Path) -> str:
    quoted = quote_zsh(path)
    return (
        f"if [[ ! -r {quoted} ]]; then\n"
        f"  print -u2 -- 'zshenv: unreadable file: {path}'\n"
        "  return 1\n"
        "fi\n"
        f"source {quoted}\n"
    )


def resolve(config: dict[str, Any]) -> list[tuple[str, str, Path | None]]:
    shell = config["shell"]
    return [(name, *parse_segment(name, shell.get(name, {}))) for name in SEGMENTS]


def render(config: dict[str, Any], output: Path) -> None:
    output.mkdir(parents=True, exist_ok=True)
    for index, (name, mode, custom) in enumerate(resolve(config), 10):
        if custom is not None and not custom.is_file():
            fail(f"custom file not found: {custom}")
        if mode == "disabled":
            continue

        content = "# Generated by zshenv. Do not edit.\n"
        if name == "prompt" and mode == "replace":
            if shutil.which("starship") is None:
                fail("starship is selected with a custom config but is not installed")
            content += f"export STARSHIP_CONFIG={quote_zsh(custom)}\n"
            content += 'eval "$(starship init zsh)"\n'
        else:
            if mode in {"default", "extend"}:
                default_file = DEFAULT_FILES[name]
                if not default_file.is_file():
                    fail(f"default segment not installed: {default_file}")
                content += source_line(default_file)
            if mode in {"replace", "extend"} and custom is not None:
                content += source_line(custom)

        target = output / f"{index:02d}-{name}.zsh"
        target.write_text(content, encoding="utf-8")


def validate_zsh(path: Path) -> None:
    if shutil.which("zsh") is None:
        fail("zsh is not installed")
    for file in sorted(path.glob("*.zsh")):
        run("zsh", "-n", str(file))


def install_defaults() -> None:
    if shutil.which("chezmoi") is None:
        fail("chezmoi is required; see README")
    run("chezmoi", "--source", str(ROOT), "apply")


def detect_conflicts(path: Path) -> list[str]:
    if not path.is_file():
        return []
    text = path.read_text(encoding="utf-8", errors="replace")
    return [
        name
        for name, pattern in CONFLICT_PATTERNS.items()
        if re.search(pattern, text, re.MULTILINE | re.IGNORECASE)
    ]


def ensure_layout() -> None:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    CUSTOM_DIR.mkdir(parents=True, exist_ok=True)
    if not CONFIG_FILE.exists():
        shutil.copy2(ROOT / "config" / "shell.default.yaml", CONFIG_FILE)


def atomic_apply(config_path: Path) -> None:
    config = load_config(config_path)
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=".generated.", dir=CONFIG_DIR))
    previous = CONFIG_DIR / ".generated.previous"
    try:
        render(config, staging)
        validate_zsh(staging)
        if previous.exists():
            shutil.rmtree(previous)
        if GENERATED_DIR.exists():
            GENERATED_DIR.rename(previous)
        staging.rename(GENERATED_DIR)
        if previous.exists():
            shutil.rmtree(previous)
    except BaseException:
        if staging.exists():
            shutil.rmtree(staging)
        if not GENERATED_DIR.exists() and previous.exists():
            previous.rename(GENERATED_DIR)
        raise
    print("Applied shell configuration.")


def cmd_init(args: argparse.Namespace) -> None:
    existing = LOADER.is_file() and MARKER not in LOADER.read_text(encoding="utf-8", errors="replace")
    conflicts = detect_conflicts(LOADER) if existing else []

    if existing and not args.adopt and not args.replace:
        print("Existing ~/.zshrc detected. No active files were changed.")
        if conflicts:
            print("Potential conflicts:")
            for item in conflicts:
                print(f"  - {item}")
        print("Choose: `python3 ./zshenv init --adopt` or `python3 ./zshenv init --replace`.")
        raise SystemExit(3)

    ensure_layout()
    if existing:
        timestamp = dt.datetime.now().strftime("%Y%m%dT%H%M%S")
        backup = LOADER.with_name(f".zshrc.backup-{timestamp}")
        shutil.copy2(LOADER, backup)
        print(f"Backup: {backup}")
        if args.adopt:
            migrated = CUSTOM_DIR / "migrated.zsh"
            if migrated.exists():
                fail(f"refusing to overwrite existing migration: {migrated}")
            shutil.copy2(LOADER, migrated)
            print(f"Preserved existing config: {migrated}")

    install_defaults()
    atomic_apply(Path(args.config).expanduser())
    if conflicts:
        print("Potential conflicts remain user-owned; zshenv did not resolve them.")


def cmd_check(args: argparse.Namespace) -> None:
    config_path = Path(args.config).expanduser()
    config = load_config(config_path)
    with tempfile.TemporaryDirectory(prefix="zshenv-check-") as temp:
        rendered = Path(temp)
        render(config, rendered)
        validate_zsh(rendered)
    print("[ok] configuration")
    print("[ok] generated Zsh syntax")
    for command in OPTIONAL_COMMANDS:
        print(f"[{'ok' if shutil.which(command) else 'skip'}] {command}")


def cmd_diff(args: argparse.Namespace) -> None:
    config = load_config(Path(args.config).expanduser())
    with tempfile.TemporaryDirectory(prefix="zshenv-diff-") as temp:
        rendered = Path(temp)
        render(config, rendered)
        old = {p.name: p.read_text(encoding="utf-8").splitlines(True) for p in GENERATED_DIR.glob("*.zsh")} if GENERATED_DIR.exists() else {}
        new = {p.name: p.read_text(encoding="utf-8").splitlines(True) for p in rendered.glob("*.zsh")}
        changed = False
        for name in sorted(set(old) | set(new)):
            diff = list(difflib.unified_diff(old.get(name, []), new.get(name, []), f"a/{name}", f"b/{name}"))
            if diff:
                changed = True
                sys.stdout.writelines(diff)
        if not changed:
            print("No generated changes.")


def cmd_status(args: argparse.Namespace) -> None:
    config_path = Path(args.config).expanduser()
    managed = LOADER.is_file() and MARKER in LOADER.read_text(encoding="utf-8", errors="replace")
    print(f"Config:    {config_path}")
    print(f"Loader:    {'managed' if managed else 'unmanaged'}")
    print(f"Generated: {'present' if GENERATED_DIR.is_dir() else 'missing'}")
    print(f"Custom:    {len(list(CUSTOM_DIR.iterdir())) if CUSTOM_DIR.is_dir() else 0} files")


def main() -> None:
    parser = argparse.ArgumentParser(prog="zshenv")
    parser.add_argument("--config", default=str(CONFIG_FILE))
    sub = parser.add_subparsers(dest="command", required=True)

    init = sub.add_parser("init")
    choice = init.add_mutually_exclusive_group()
    choice.add_argument("--adopt", action="store_true")
    choice.add_argument("--replace", action="store_true")
    init.set_defaults(func=cmd_init)

    sub.add_parser("apply").set_defaults(func=lambda a: atomic_apply(Path(a.config).expanduser()))
    sub.add_parser("check").set_defaults(func=cmd_check)
    sub.add_parser("diff").set_defaults(func=cmd_diff)
    sub.add_parser("status").set_defaults(func=cmd_status)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
