#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    print("zshenv: PyYAML is required (python3 -m pip install --user pyyaml)", file=sys.stderr)
    raise SystemExit(2)

ROOT = Path(__file__).resolve().parent
HOME = Path.home()
CONFIG_DIR = Path(os.environ.get("XDG_CONFIG_HOME", HOME / ".config")) / "zsh"
CONFIG_FILE = CONFIG_DIR / "shell.yaml"
GENERATED_DIR = CONFIG_DIR / "generated"
CUSTOM_DIR = CONFIG_DIR / "custom"
LOADER = HOME / ".zshrc"
MARKER = "# managed-by: zshenv"
SEGMENTS = ["core", "paths", "completion", "runtimes", "remote", "aliases", "prompt", "ux"]
DEFAULT_FILES = {
    "core": CONFIG_DIR / "core.zsh",
    "paths": CONFIG_DIR / "paths.zsh",
    "completion": CONFIG_DIR / "completion.zsh",
    "runtimes": CONFIG_DIR / "runtimes.zsh",
    "remote": CONFIG_DIR / "remote.zsh",
    "aliases": CONFIG_DIR / "aliases.zsh",
    "prompt": CONFIG_DIR / "prompt.zsh",
    "ux": CONFIG_DIR / "ux.zsh",
}
CONFLICT_PATTERNS = {
    "prompt initialization": r"(starship init|oh-my-posh init|powerlevel10k|p10k)",
    "runtime integration": r"(mise activate|pyenv init|nvm\.sh)",
    "directory integration": r"(zoxide init|direnv hook|atuin init)",
    "completion initialization": r"\bcompinit\b",
    "aliases": r"^\s*alias\s+",
    "keybindings": r"\bbindkey\b",
}


def fail(message: str, code: int = 1) -> None:
    print(f"zshenv: {message}", file=sys.stderr)
    raise SystemExit(code)


def run(*args: str, check: bool = True, capture: bool = False) -> subprocess.CompletedProcess[str]:
    return subprocess.run(args, check=check, text=True, capture_output=capture)


def expand_path(value: str) -> Path:
    if any(token in value for token in ("$(`", "`", "${", "$((")):
        fail(f"unsafe path: {value}")
    path = Path(value).expanduser()
    if not path.is_absolute():
        fail(f"path must be absolute or start with ~: {value}")
    return path


def load_config(path: Path) -> dict[str, Any]:
    if not path.is_file():
        fail(f"config not found: {path}")
    try:
        data = yaml.safe_load(path.read_text()) or {}
    except yaml.YAMLError as exc:
        fail(f"invalid YAML: {exc}")
    if data.get("version") != 1 or not isinstance(data.get("shell"), dict):
        fail("config must contain version: 1 and a shell mapping")
    unknown = set(data["shell"]) - set(SEGMENTS)
    if unknown:
        fail(f"unknown shell segments: {', '.join(sorted(unknown))}")
    return data


def parse_segment(name: str, value: Any) -> tuple[str, Path | None]:
    if value is None or value == {}:
        return "default", None
    if value is False:
        return "disabled", None
    if not isinstance(value, dict):
        fail(f"shell.{name} must be an object or false")
    if name == "prompt":
        if "extend" in value:
            fail("shell.prompt does not support extend")
        engine = value.get("engine", "starship")
        if engine != "starship":
            fail(f"unsupported prompt engine: {engine}")
        if "path" in value:
            return "replace", expand_path(str(value["path"]))
        return "default", None
    if "path" in value and "extend" in value:
        fail(f"shell.{name} cannot contain both path and extend")
    if "path" in value:
        return "replace", expand_path(str(value["path"]))
    if "extend" in value:
        ext = value["extend"]
        if not isinstance(ext, dict) or "path" not in ext:
            fail(f"shell.{name}.extend.path is required")
        return "extend", expand_path(str(ext["path"]))
    fail(f"shell.{name} must be empty, false, path, or extend.path")


def source_line(path: Path) -> str:
    quoted = str(path).replace("'", "'\\''")
    return f"[[ -r '{quoted}' ]] || {{ print -u2 -- 'zshenv: unreadable file: {quoted}'; return 1; }}\nsource '{quoted}'\n"


def render(config: dict[str, Any], output: Path) -> None:
    output.mkdir(parents=True, exist_ok=True)
    shell = config["shell"]
    for index, name in enumerate(SEGMENTS, 10):
        mode, custom = parse_segment(name, shell.get(name, {}))
        if custom is not None and not custom.is_file():
            fail(f"custom file not found: {custom}")
        if mode == "disabled":
            continue
        content = "# Generated by zshenv. Do not edit.\n"
        if name == "prompt" and mode == "replace":
            if shutil.which("starship") is None:
                fail("starship is selected but not installed")
            content += f"export STARSHIP_CONFIG='{str(custom).replace(chr(39), chr(39)+chr(92)+chr(39)+chr(39))}'\neval \"$(starship init zsh)\"\n"
        else:
            if mode in ("default", "extend"):
                default_file = DEFAULT_FILES[name]
                if not default_file.is_file():
                    fail(f"default segment not installed: {default_file}")
                content += source_line(default_file)
            if mode in ("replace", "extend") and custom is not None:
                content += source_line(custom)
        (output / f"{index:02d}-{name}.zsh").write_text(content)


def validate_rendered(path: Path) -> None:
    files = sorted(path.glob("*.zsh"))
    for file in files:
        run("zsh", "-n", str(file))
    probe = "setopt NO_RCS; for f in $1/*.zsh(N); do source $f || exit 1; done"
    run("zsh", "-dfc", probe, "zshenv-check", str(path))


def install_defaults() -> None:
    if shutil.which("chezmoi") is None:
        fail("chezmoi is required; see README")
    run("chezmoi", "--source", str(ROOT), "apply")


def detect_conflicts(path: Path) -> list[str]:
    if not path.is_file():
        return []
    text = path.read_text(errors="replace")
    return [name for name, pattern in CONFLICT_PATTERNS.items() if re.search(pattern, text, re.MULTILINE | re.IGNORECASE)]


def ensure_config() -> None:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    CUSTOM_DIR.mkdir(parents=True, exist_ok=True)
    if not CONFIG_FILE.exists():
        shutil.copy2(ROOT / "config" / "shell.default.yaml", CONFIG_FILE)


def atomic_apply(config_path: Path) -> None:
    config = load_config(config_path)
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix=".generated.", dir=CONFIG_DIR) as temp:
        staging = Path(temp)
        render(config, staging)
        validate_rendered(staging)
        previous = CONFIG_DIR / ".generated.previous"
        if previous.exists():
            shutil.rmtree(previous)
        if GENERATED_DIR.exists():
            GENERATED_DIR.rename(previous)
        staging.rename(GENERATED_DIR)
        if previous.exists():
            shutil.rmtree(previous)
    print("Applied shell configuration.")


def cmd_init(args: argparse.Namespace) -> None:
    conflicts = []
    existing = LOADER.is_file() and MARKER not in LOADER.read_text(errors="replace")
    if existing:
        conflicts = detect_conflicts(LOADER)
        if not args.adopt and not args.replace:
            print("Existing ~/.zshrc detected. No active files were changed.")
            if conflicts:
                print("Potential conflicts:")
                for item in conflicts:
                    print(f"  - {item}")
            print("Run `./zshenv init --adopt` to preserve and load it, or `--replace` to keep only the backup.")
            raise SystemExit(3)
        backup = LOADER.with_name(f".zshrc.backup-{__import__('datetime').datetime.now().strftime('%Y%m%dT%H%M%S')}")
        shutil.copy2(LOADER, backup)
        print(f"Backup: {backup}")
        if args.adopt:
            CUSTOM_DIR.mkdir(parents=True, exist_ok=True)
            migrated = CUSTOM_DIR / "migrated.zsh"
            if migrated.exists():
                fail(f"refusing to overwrite: {migrated}")
            shutil.copy2(LOADER, migrated)
            print(f"Preserved existing config: {migrated}")
    ensure_config()
    install_defaults()
    atomic_apply(Path(args.config).expanduser())
    if conflicts:
        print("Review reported conflicts; zshenv does not resolve them automatically.")


def cmd_check(args: argparse.Namespace) -> None:
    if shutil.which("zsh") is None:
        fail("zsh is not installed")
    config = load_config(Path(args.config).expanduser())
    with tempfile.TemporaryDirectory(prefix="zshenv-check-") as temp:
        render(config, Path(temp))
        validate_rendered(Path(temp))
    print("Configuration is valid.")
    for command in ("fzf", "zoxide", "mise", "docker", "kubectl"):
        state = "ok" if shutil.which(command) else "skip"
        print(f"[{state}] {command}")


def cmd_diff(args: argparse.Namespace) -> None:
    config = load_config(Path(args.config).expanduser())
    with tempfile.TemporaryDirectory(prefix="zshenv-diff-") as temp:
        rendered = Path(temp)
        render(config, rendered)
        old = {p.name: p.read_text().splitlines(True) for p in GENERATED_DIR.glob("*.zsh")} if GENERATED_DIR.exists() else {}
        new = {p.name: p.read_text().splitlines(True) for p in rendered.glob("*.zsh")}
        for name in sorted(set(old) | set(new)):
            sys.stdout.writelines(difflib.unified_diff(old.get(name, []), new.get(name, []), f"a/{name}", f"b/{name}"))


def cmd_status(args: argparse.Namespace) -> None:
    print(f"Config:    {Path(args.config).expanduser()}")
    print(f"Loader:    {'managed' if LOADER.is_file() and MARKER in LOADER.read_text(errors='replace') else 'unmanaged'}")
    print(f"Generated: {'present' if GENERATED_DIR.is_dir() else 'missing'}")
    print(f"Custom:    {len(list(CUSTOM_DIR.glob('*'))) if CUSTOM_DIR.is_dir() else 0} files")


def main() -> None:
    parser = argparse.ArgumentParser(prog="zshenv")
    parser.add_argument("--config", default=str(CONFIG_FILE))
    sub = parser.add_subparsers(dest="command", required=True)
    init = sub.add_parser("init")
    group = init.add_mutually_exclusive_group()
    group.add_argument("--adopt", action="store_true")
    group.add_argument("--replace", action="store_true")
    init.set_defaults(func=cmd_init)
    sub.add_parser("apply").set_defaults(func=lambda a: atomic_apply(Path(a.config).expanduser()))
    sub.add_parser("check").set_defaults(func=cmd_check)
    sub.add_parser("diff").set_defaults(func=cmd_diff)
    sub.add_parser("status").set_defaults(func=cmd_status)
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
