# Shell
alias ll='ls -lah'
alias reload='exec zsh -l'

# Git
alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gb='git branch'
alias gc='git commit'
alias gca='git commit --amend'
alias gcl='git clone'
alias gco='git checkout'
alias gd='git diff'
alias gds='git diff --staged'
alias gf='git fetch --all --prune'
alias gl='git pull'
alias glog='git log --graph --decorate --oneline --all'
alias gp='git push'
alias gr='git restore'
alias gss='git status --short --branch'
alias gst='git status'
alias gsw='git switch'
alias gswc='git switch -c'
